const fs = require("fs");
const width = 1000;
const height = 1000;
const dir = __dirname;
const description = "Shit Heads test set.";
const baseImageUri = "https://shitheads/nft";
const startEditionFrom = 1;
const endEditionAt = 100;
const editionSize = 100;
const raceWeights = [
  {
    value: "shitheads",
    from: 1,
    to: editionSize,
  },
];

const races = {
  shitheads: {
    name: "Shit Heads",
    layers: [
      {
        name: "Background",
        elements: [
          {
            id: 0,
            name: "Light blue",
            path: `${dir}/1-background/BG_Blue.png`,
            weight: 10,
          },
          {
            id: 1,
            name: "Off white",
            path: `${dir}/1-background/BG_Offwhite.png`,
            weight: 15,
          },
          {
            id: 2,
            name: "Purple",
            path: `${dir}/1-background/BG_Purple.png`,
            weight: 20,
          },
          {
            id: 3,
            name: "Yellow",
            path: `${dir}/1-background/BG_Yellow.png`,
            weight: 25,
          },
        ],
        position: { x: 0, y: 0 },
        size: { width: width, height: height },
      },
      {
        name: "Type",
        elements: [
          {
            id: 0,
            name: "Black",
            path: `${dir}/2-type/type_black.png`,
            weight: 10,
          },
          {
            id: 1,
            name: "Brown",
            path: `${dir}/2-type/type_brown.png`,
            weight: 10,
          },
          {
            id: 2,
            name: "Bubble",
            path: `${dir}/2-type/type_bubble.png`,
            weight: 22,
          },
          {
            id: 3,
            name: "Ghost",
            path: `${dir}/2-type/type_ghost.png`,
            weight: 18,
          },
          {
            id: 4,
            name: "Gold",
            path: `${dir}/2-type/type_gold.png`,
            weight: 15,
          },
          {
            id: 5,
            name: "Mummy",
            path: `${dir}/2-type/type_mummy.png`,
            weight: 25,
          },
          {
            id: 6,
            name: "Robot",
            path: `${dir}/2-type/type_robot.png`,
            weight: 30,
          },
          {
            id: 7,
            name: "Snow",
            path: `${dir}/2-type/type_snow.png`,
            weight: 35,
          },
          {
            id: 8,
            name: "Spanked",
            path: `${dir}/2-type/type_spanked.png`,
            weight: 65,
          },
          {
            id: 9,
            name: "Stone",
            path: `${dir}/2-type/type_stone.png`,
            weight: 40,
          },
          {
            id: 10,
            name: "Tan",
            path: `${dir}/2-type/type_tan.png`,
            weight: 10,
          },
          {
            id: 11,
            name: "Tiedye",
            path: `${dir}/2-type/type_tiedye.png`,
            weight: 20,
          },
          {
            id: 12,
            name: "white",
            path: `${dir}/2-type/type_white.png`,
            weight: 10,
          },
        ],
        position: { x: 0, y: 0 },
        size: { width: width, height: height },
      },
      {
        name: "Tramp stamp",
        elements: [
          {
            id: 0,
            name: "Blush",
            path: `${dir}/3-tramp/TS_Blush.png`,
            weight: 25,
          },
          {
            id: 1,
            name: "Caution",
            path: `${dir}/3-tramp/TS_Caution.png`,
            weight: 30,
          },
          {
            id: 2,
            name: "Hand",
            path: `${dir}/3-tramp/TS_Hand.png`,
            weight: 40,
          },
          {
            id: 3,
            name: "Lips",
            path: `${dir}/3-tramp/TS_Lips.png`,
            weight: 42,
          },
          {
            id: 4,
            name: "Milk",
            path: `${dir}/3-tramp/TS_Milk.png`,
            weight: 44,
          },
          {
            id: 5,
            name: "Paper",
            path: `${dir}/3-tramp/TS_Paper.png`,
            weight: 12,
          },
          {
            id: 6,
            name: "Ragret",
            path: `${dir}/3-tramp/TS_Regret.png`,
            weight: 46,
          },
          {
            id: 7,
            name: "Shopping",
            path: `${dir}/3-tramp/TS_Shopping.png`,
            weight: 48,
          },
          {
            id: 8,
            name: "Skull",
            path: `${dir}/3-tramp/TS_Skull.png`,
            weight: 52,
          },
          {
            id: 9,
            name: "Weed",
            path: `${dir}/3-tramp/TS_Weed.png`,
            weight: 23,
          },
          {
            id: 10,
            name: "XXX",
            path: `${dir}/3-tramp/TS_XXX.png`,
            weight: 11,
          },
        ],
        position: { x: 0, y: 0 },
        size: { width: width, height: height },
      },
      {
        name: "Birthmark",
        elements: [
          {
            id: 0,
            name: "Hair",
            path: `${dir}/4-birthmark/B_Hair.PNG`,
            weight: 15,
          },
          {
            id: 1,
            name: "Mole",
            path: `${dir}/4-birthmark/B_Mole.PNG`,
            weight: 10,
          },
          {
            id: 2,
            name: "Scars",
            path: `${dir}/4-birthmark/B_Scars.PNG`,
            weight: 5,
          },{
            id: 3,
            name: "Shiny",
            path: `${dir}/4-birthmark/B_Shiny.PNG`,
            weight: 30,
          },{
            id: 4,
            name: "Stitches",
            path: `${dir}/4-birthmark/B_Stitches.PNG`,
            weight: 35,
          },
        ],
        position: { x: 0, y: 0 },
        size: { width: width, height: height },
      },
      {
        name: "Socks",
        elements: [
          {
            id: 0,
            name: "Assless",
            path: `${dir}/5-socks/S_Assless.PNG`,
            weight: 15,
          },
          {
            id: 1,
            name: "Black",
            path: `${dir}/5-socks/S_Black.PNG`,
            weight: 50,
          },
          {
            id: 2,
            name: "Black Bandana",
            path: `${dir}/5-socks/S_BlackBandana.PNG`,
            weight: 55,
          },
          {
            id: 3,
            name: "Blue Bandana",
            path: `${dir}/5-socks/S_BlueBandana.PNG`,
            weight: 56,
          },
          {
            id: 4,
            name: "Blue Tie",
            path: `${dir}/5-socks/S_BlueTie.PNG`,
            weight: 57,
          },
          {
            id: 5,
            name: "Bones",
            path: `${dir}/5-socks/S_Bones.PNG`,
            weight: 24,
          },
          {
            id: 6,
            name: "Cat",
            path: `${dir}/5-socks/S_Cat.PNG`,
            weight: 26,
          },
          {
            id: 7,
            name: "Catdog",
            path: `${dir}/5-socks/S_Catdog.PNG`,
            weight: 12,
          },
          {
            id: 8,
            name: "Dog Collar",
            path: `${dir}/5-socks/S_Dogcollar.PNG`,
            weight: 10,
          },
          {
            id: 9,
            name: "Eat Bandana",
            path: `${dir}/5-socks/S_EatBandana.PNG`,
            weight: 18,
          },
          {
            id: 10,
            name: "Fire",
            path: `${dir}/5-socks/S_Fire.PNG`,
            weight: 37,
          },
          {
            id: 11,
            name: "Green Bandana",
            path: `${dir}/5-socks/S_GreenBandana.PNG`,
            weight: 62,
          },
          {
            id: 12,
            name: "Pink Bandana",
            path: `${dir}/5-socks/S_PinkBandana.PNG`,
            weight: 64,
          },
          {
            id: 13,
            name: "Purple Tie",
            path: `${dir}/5-socks/S_PurpleTie.PNG`,
            weight: 59,
          },
          {
            id: 14,
            name: "Sports",
            path: `${dir}/5-socks/S_Sports.PNG`,
            weight: 19,
          },
        ],
        position: { x: 0, y: 0 },
        size: { width: width, height: height },
      },
      {
        name: "Eyes",
        elements: [
          {
            id: 0,
            name: "3D",
            path: `${dir}/6-eyes/E_3D.PNG`,
            weight: 0,
          },
          {
            id: 1,
            name: "Bacon & Egg",
            path: `${dir}/6-eyes/E_Baconandegg.PNG`,
            weight: 15,
          },
          {
            id: 2,
            name: "Bender",
            path: `${dir}/6-eyes/E_Bender.PNG`,
            weight: 12,
          },
          {
            id: 3,
            name: "Kanye (Black)",
            path: `${dir}/6-eyes/E_Blackkanye.PNG`,
            weight: 13,
          },
          {
            id: 4,
            name: "Black Sash",
            path: `${dir}/6-eyes/E_BlackSash.PNG`,
            weight: 17,
          },
          {
            id: 5,
            name: "Black Stache",
            path: `${dir}/6-eyes/E_Blackstache.PNG`,
            weight: 20,
          },
          {
            id: 6,
            name: "Blunt",
            path: `${dir}/6-eyes/E_Blunt.PNG`,
            weight: 16,
          },
          {
            id: 7,
            name: "BopIt",
            path: `${dir}/6-eyes/E_BopIt.PNG`,
            weight: 21,
          },
          {
            id: 8,
            name: "Bubble Glasses",
            path: `${dir}/6-eyes/E_Bubbleglasses.PNG`,
            weight: 27,
          },
          {
            id: 9,
            name: "Bubble Gum",
            path: `${dir}/6-eyes/E_Bubblegum.PNG`,
            weight: 8,
          },
          {
            id: 10,
            name: "Cactus",
            path: `${dir}/6-eyes/E_Cactus.PNG`,
            weight: 32,
          },
          {
            id: 11,
            name: "Carrot",
            path: `${dir}/6-eyes/E_Carrot.PNG`,
            weight: 24,
          },
          {
            id: 12,
            name: "Cat",
            path: `${dir}/6-eyes/E_Cat.PNG`,
            weight: 7,
          },
          {
            id: 13,
            name: "Cigar",
            path: `${dir}/6-eyes/E_Cigar.PNG`,
            weight: 12,
          },
          {
            id: 14,
            name: "Coach",
            path: `${dir}/6-eyes/E_Coach.PNG`,
            weight: 25,
          },
          {
            id: 15,
            name: "Deal With It",
            path: `${dir}/6-eyes/E_Dealwithit.PNG`,
            weight: 15,
          },
          {
            id: 16,
            name: "Dog Nose",
            path: `${dir}/6-eyes/E_DogNose.PNG`,
            weight: 8,
          },
          {
            id: 17,
            name: "Eye",
            path: `${dir}/6-eyes/E_Eye.PNG`,
            weight: 19,
          },
          {
            id: 18,
            name: "Fish",
            path: `${dir}/6-eyes/E_Fish.PNG`,
            weight: 4,
          },
          {
            id: 19,
            name: "Flames",
            path: `${dir}/6-eyes/E_Flames.PNG`,
            weight: 22,
          },
          {
            id: 20,
            name: "Flashlight",
            path: `${dir}/6-eyes/E_Flashlight.PNG`,
            weight: 24,
          },
          {
            id: 21,
            name: "Foot",
            path: `${dir}/6-eyes/E_Foot.PNG`,
            weight: 18,
          },
          {
            id: 22,
            name: "Game",
            path: `${dir}/6-eyes/E_Game.PNG`,
            weight: 28,
          },
          {
            id: 23,
            name: "Gas",
            path: `${dir}/6-eyes/E_Gas.PNG`,
            weight: 24,
          },
          {
            id: 24,
            name: "Gerbil",
            path: `${dir}/6-eyes/E_Gerbil.PNG`,
            weight: 22,
          },
          {
            id: 25,
            name: "Ghost",
            path: `${dir}/6-eyes/E_Ghost.PNG`,
            weight: 15,
          },
          {
            id: 26,
            name: "Goose",
            path: `${dir}/6-eyes/E_Goose.PNG`,
            weight: 15,
          },
          {
            id: 27,
            name: "Hotdog",
            path: `${dir}/6-eyes/E_Hotdog.PNG`,
            weight: 13,
          },
          {
            id: 28,
            name: "Hulgan",
            path: `${dir}/6-eyes/E_Hulgan.PNG`,
            weight: 27,
          },
          {
            id: 29,
            name: "Lightbulb",
            path: `${dir}/6-eyes/E_Lightbulb.PNG`,
            weight: 23,
          },
          {
            id: 30,
            name: "Lightning",
            path: `${dir}/6-eyes/E_Lightning.PNG`,
            weight: 4,
          },
          {
            id: 31,
            name: "Magican Tissue",
            path: `${dir}/6-eyes/E_Magicantissue.PNG`,
            weight: 19,
          },
          {
            id: 32,
            name: "Monocle",
            path: `${dir}/6-eyes/E_Monocle.PNG`,
            weight: 18,
          },
          {
            id: 33,
            name: "Pacifier",
            path: `${dir}/6-eyes/E_Pacifier.PNG`,
            weight: 15,
          },
          {
            id: 34,
            name: "Pickle",
            path: `${dir}/6-eyes/E_Pickle.PNG`,
            weight: 15,
          },
          {
            id: 35,
            name: "Kanye (Pink)",
            path: `${dir}/6-eyes/E_Pinkkanye.PNG`,
            weight: 20,
          },
          {
            id: 36,
            name: "Pirate",
            path: `${dir}/6-eyes/E_Pirate.PNG`,
            weight: 10,
          },
          {
            id: 37,
            name: "Portal",
            path: `${dir}/6-eyes/E_Portal.PNG`,
            weight: 8,
          },
          {
            id: 38,
            name: "Pride",
            path: `${dir}/6-eyes/E_Pride.PNG`,
            weight: 12,
          },
          {
            id: 39,
            name: "Purple Sash",
            path: `${dir}/6-eyes/E_PurpleSash.PNG`,
            weight: 20,
          },
          {
            id: 40,
            name: "Revolver",
            path: `${dir}/6-eyes/E_Revolver.PNG`,
            weight: 5,
          },
          {
            id: 41,
            name: "Saxaphone",
            path: `${dir}/6-eyes/E_Saxaphone.PNG`,
            weight: 15,
          },
          {
            id: 42,
            name: "Snake",
            path: `${dir}/6-eyes/E_Snake.PNG`,
            weight: 15,
          },
          {
            id: 43,
            name: "Sparkler",
            path: `${dir}/6-eyes/E_Sparkler.PNG`,
            weight: 15,
          },
          {
            id: 44,
            name: "Squirtle",
            path: `${dir}/6-eyes/E_Squirtle.PNG`,
            weight: 25,
          },
          {
            id: 45,
            name: "Theometer",
            path: `${dir}/6-eyes/E_Theometer.PNG`,
            weight: 17,
          },
          {
            id: 46,
            name: "Throwup",
            path: `${dir}/6-eyes/E_Throwup.PNG`,
            weight: 18,
          },
          {
            id: 47,
            name: "Throwup (Rainbow)",
            path: `${dir}/6-eyes/E_Throwuprainbow.PNG`,
            weight: 9,
          },
          {
            id: 48,
            name: "Toilet Paper",
            path: `${dir}/6-eyes/E_Toiletpaper.PNG`,
            weight: 15,
          },
          {
            id: 49,
            name: "Tongue",
            path: `${dir}/6-eyes/E_Tongue.PNG`,
            weight: 16,
          },
          {
            id: 50,
            name: "Twig",
            path: `${dir}/6-eyes/E_Twig.PNG`,
            weight: 17,
          },
          {
            id: 51,
            name: "Wheat",
            path: `${dir}/6-eyes/E_Wheat.PNG`,
            weight: 18,
          },
          {
            id: 52,
            name: "Kanye (White)",
            path: `${dir}/6-eyes/E_Whitekanye.PNG`,
            weight: 19,
          },
          {
            id: 53,
            name: "Kanye (Yellow)",
            path: `${dir}/6-eyes/E_Yellowkanye.PNG`,
            weight: 20,
          },
        ],
        position: { x: 0, y: 0 },
        size: { width: width, height: height },
      },
      {
        name: "Head",
        elements: [
          {
            id: 0,
            name: "Birthday",
            path: `${dir}/7-head/H_BDay.PNG`,
            weight: 5,
          },
          {
            id: 1,
            name: "Beanie",
            path: `${dir}/7-head/H_Beanie.PNG`,
            weight: 10,
          },
          {
            id: 2,
            name: "Beer",
            path: `${dir}/7-head/H_Beer.PNG`,
            weight: 15,
          },
          {
            id: 3,
            name: "Black Mustache",
            path: `${dir}/7-head/H_BlackMustache.PNG`,
            weight: 25,
          },
          {
            id: 4,
            name: "Blue Mohawk",
            path: `${dir}/7-head/H_BlueMohawk.PNG`,
            weight: 35,
          },
          {
            id: 5,
            name: "Blue Sash",
            path: `${dir}/7-head/H_BlueSash.PNG`,
            weight: 45,
          },
          {
            id: 6,
            name: "Construction",
            path: `${dir}/7-head/H_Construction.PNG`,
            weight: 55,
          },
          {
            id: 7,
            name: "Cowboy",
            path: `${dir}/7-head/H_Cowboy.PNG`,
            weight: 44,
          },
          {
            id: 8,
            name: "Dog (Brown)",
            path: `${dir}/7-head/H_Dogbrown.PNG`,
            weight: 33,
          },
          {
            id: 9,
            name: "Dragon",
            path: `${dir}/7-head/H_Dragon.PNG`,
            weight: 5,
          },
          {
            id: 10,
            name: "Dunce",
            path: `${dir}/7-head/H_Dunce.PNG`,
            weight: 5,
          },
          {
            id: 11,
            name: "Fatass",
            path: `${dir}/7-head/H_Fatass.PNG`,
            weight: 5,
          },
          {
            id: 12,
            name: "Football",
            path: `${dir}/7-head/H_Football.PNG`,
            weight: 5,
          },
          {
            id: 13,
            name: "Frat",
            path: `${dir}/7-head/H_Frat.PNG`,
            weight: 5,
          },
          {
            id: 14,
            name: "Fro",
            path: `${dir}/7-head/H_Fro.PNG`,
            weight: 5,
          },
          {
            id: 15,
            name: "Green Mohawk",
            path: `${dir}/7-head/H_GreenMohawk.PNG`,
            weight: 5,
          },
          {
            id: 16,
            name: "Halo",
            path: `${dir}/7-head/H_Halo.PNG`,
            weight: 5,
          },
          {
            id: 17,
            name: "Leela",
            path: `${dir}/7-head/H_Leela.PNG`,
            weight: 5,
          },
          {
            id: 18,
            name: "Marge",
            path: `${dir}/7-head/H_Marge.PNG`,
            weight: 5,
          },
          {
            id: 19,
            name: "Mick",
            path: `${dir}/7-head/H_Mick.PNG`,
            weight: 5,
          },
          {
            id: 20,
            name: "Mouse",
            path: `${dir}/7-head/H_Mouse.PNG`,
            weight: 5,
          },
          {
            id: 21,
            name: "Mullet",
            path: `${dir}/7-head/H_Mullet.PNG`,
            weight: 5,
          },
          {
            id: 22,
            name: "Nowhere",
            path: `${dir}/7-head/H_Nowhere.PNG`,
            weight: 5,
          },
          {
            id: 23,
            name: "Puppy",
            path: `${dir}/7-head/H_Puppy.PNG`,
            weight: 5,
          },
          {
            id: 24,
            name: "Purple Mohawk",
            path: `${dir}/7-head/H_PurpleMohawk.PNG`,
            weight: 5,
          },
          {
            id: 25,
            name: "Red Mohawk",
            path: `${dir}/7-head/H_RedMohawk.PNG`,
            weight: 5,
          },
          {
            id: 26,
            name: "Red Sash",
            path: `${dir}/7-head/H_RedSash.PNG`,
            weight: 5,
          },
          {
            id: 27,
            name: "Rick",
            path: `${dir}/7-head/H_Rick.PNG`,
            weight: 5,
          },
          {
            id: 28,
            name: "Tuppee",
            path: `${dir}/7-head/H_Tuppee.PNG`,
            weight: 5,
          },
          {
            id: 29,
            name: "Wendy",
            path: `${dir}/7-head/H_Wendy.PNG`,
            weight: 5,
          },
          {
            id: 30,
            name: "Wizard",
            path: `${dir}/7-head/H_Wizard.PNG`,
            weight: 5,
          },
        ],
        position: { x: 0, y: 0 },
        size: { width: width, height: height },
      },
      {
        name: "Ass Kisser",
        elements: [
          {
            id: 0,
            name: "Among Them",
            path: `${dir}/8-asskisser/SH_Among.PNG`,
            weight: 10,
          },
          {
            id: 1,
            name: "Bloody Paper",
            path: `${dir}/8-asskisser/SH_BloodyPaper.PNG`,
            weight: 10,
          },
          {
            id: 2,
            name: "Dirty Paper",
            path: `${dir}/8-asskisser/SH_DirtyPaper.PNG`,
            weight: 10,
          },
          {
            id: 3,
            name: "Emoji",
            path: `${dir}/8-asskisser/SH_Emoji.PNG`,
            weight: 10,
          },
          {
            id: 4,
            name: "Fairy",
            path: `${dir}/8-asskisser/SH_Fairy.PNG`,
            weight: 10,
          },
          {
            id: 5,
            name: "Gold Paper",
            path: `${dir}/8-asskisser/SH_GoldPaper.PNG`,
            weight: 10,
          },
          {
            id: 6,
            name: "Llama",
            path: `${dir}/8-asskisser/SH_Llama.PNG`,
            weight: 10,
          },
          {
            id: 7,
            name: "Paper",
            path: `${dir}/8-asskisser/SH_Paper.PNG`,
            weight: 10,
          },
          {
            id: 8,
            name: "RIP",
            path: `${dir}/8-asskisser/SH_RIP.PNG`,
            weight: 10,
          },
        ],
        position: { x: 0, y: 0 },
        size: { width: width, height: height },
      },
    ],
  },
};

module.exports = {
  width,
  height,
  description,
  baseImageUri,
  editionSize,
  startEditionFrom,
  endEditionAt,
  races,
  raceWeights,
};
